//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWindowsFormApplication.ServiceCandidates {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCandidates.CandidatesAmericaRepublicanSoap")]
    public interface CandidatesAmericaRepublicanSoap {
        
        // CODEGEN: Generating message contract since element name GetAllYearsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllYears", ReplyAction="*")]
        MyWindowsFormApplication.ServiceCandidates.GetAllYearsResponse GetAllYears(MyWindowsFormApplication.ServiceCandidates.GetAllYearsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllYears", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWindowsFormApplication.ServiceCandidates.GetAllYearsResponse> GetAllYearsAsync(MyWindowsFormApplication.ServiceCandidates.GetAllYearsRequest request);
        
        // CODEGEN: Generating message contract since element name fromYear from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCandidates", ReplyAction="*")]
        MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesResponse GetAllCandidates(MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCandidates", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesResponse> GetAllCandidatesAsync(MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllYearsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllYears", Namespace="http://tempuri.org/", Order=0)]
        public MyWindowsFormApplication.ServiceCandidates.GetAllYearsRequestBody Body;
        
        public GetAllYearsRequest() {
        }
        
        public GetAllYearsRequest(MyWindowsFormApplication.ServiceCandidates.GetAllYearsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllYearsRequestBody {
        
        public GetAllYearsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllYearsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllYearsResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWindowsFormApplication.ServiceCandidates.GetAllYearsResponseBody Body;
        
        public GetAllYearsResponse() {
        }
        
        public GetAllYearsResponse(MyWindowsFormApplication.ServiceCandidates.GetAllYearsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllYearsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyWindowsFormApplication.ServiceCandidates.ArrayOfString GetAllYearsResult;
        
        public GetAllYearsResponseBody() {
        }
        
        public GetAllYearsResponseBody(MyWindowsFormApplication.ServiceCandidates.ArrayOfString GetAllYearsResult) {
            this.GetAllYearsResult = GetAllYearsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCandidatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCandidates", Namespace="http://tempuri.org/", Order=0)]
        public MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesRequestBody Body;
        
        public GetAllCandidatesRequest() {
        }
        
        public GetAllCandidatesRequest(MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCandidatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fromYear;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tooYear;
        
        public GetAllCandidatesRequestBody() {
        }
        
        public GetAllCandidatesRequestBody(string fromYear, string tooYear) {
            this.fromYear = fromYear;
            this.tooYear = tooYear;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCandidatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCandidatesResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesResponseBody Body;
        
        public GetAllCandidatesResponse() {
        }
        
        public GetAllCandidatesResponse(MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCandidatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyWindowsFormApplication.ServiceCandidates.ArrayOfString GetAllCandidatesResult;
        
        public GetAllCandidatesResponseBody() {
        }
        
        public GetAllCandidatesResponseBody(MyWindowsFormApplication.ServiceCandidates.ArrayOfString GetAllCandidatesResult) {
            this.GetAllCandidatesResult = GetAllCandidatesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CandidatesAmericaRepublicanSoapChannel : MyWindowsFormApplication.ServiceCandidates.CandidatesAmericaRepublicanSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CandidatesAmericaRepublicanSoapClient : System.ServiceModel.ClientBase<MyWindowsFormApplication.ServiceCandidates.CandidatesAmericaRepublicanSoap>, MyWindowsFormApplication.ServiceCandidates.CandidatesAmericaRepublicanSoap {
        
        public CandidatesAmericaRepublicanSoapClient() {
        }
        
        public CandidatesAmericaRepublicanSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CandidatesAmericaRepublicanSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CandidatesAmericaRepublicanSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CandidatesAmericaRepublicanSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWindowsFormApplication.ServiceCandidates.GetAllYearsResponse MyWindowsFormApplication.ServiceCandidates.CandidatesAmericaRepublicanSoap.GetAllYears(MyWindowsFormApplication.ServiceCandidates.GetAllYearsRequest request) {
            return base.Channel.GetAllYears(request);
        }
        
        public MyWindowsFormApplication.ServiceCandidates.ArrayOfString GetAllYears() {
            MyWindowsFormApplication.ServiceCandidates.GetAllYearsRequest inValue = new MyWindowsFormApplication.ServiceCandidates.GetAllYearsRequest();
            inValue.Body = new MyWindowsFormApplication.ServiceCandidates.GetAllYearsRequestBody();
            MyWindowsFormApplication.ServiceCandidates.GetAllYearsResponse retVal = ((MyWindowsFormApplication.ServiceCandidates.CandidatesAmericaRepublicanSoap)(this)).GetAllYears(inValue);
            return retVal.Body.GetAllYearsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWindowsFormApplication.ServiceCandidates.GetAllYearsResponse> MyWindowsFormApplication.ServiceCandidates.CandidatesAmericaRepublicanSoap.GetAllYearsAsync(MyWindowsFormApplication.ServiceCandidates.GetAllYearsRequest request) {
            return base.Channel.GetAllYearsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWindowsFormApplication.ServiceCandidates.GetAllYearsResponse> GetAllYearsAsync() {
            MyWindowsFormApplication.ServiceCandidates.GetAllYearsRequest inValue = new MyWindowsFormApplication.ServiceCandidates.GetAllYearsRequest();
            inValue.Body = new MyWindowsFormApplication.ServiceCandidates.GetAllYearsRequestBody();
            return ((MyWindowsFormApplication.ServiceCandidates.CandidatesAmericaRepublicanSoap)(this)).GetAllYearsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesResponse MyWindowsFormApplication.ServiceCandidates.CandidatesAmericaRepublicanSoap.GetAllCandidates(MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesRequest request) {
            return base.Channel.GetAllCandidates(request);
        }
        
        public MyWindowsFormApplication.ServiceCandidates.ArrayOfString GetAllCandidates(string fromYear, string tooYear) {
            MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesRequest inValue = new MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesRequest();
            inValue.Body = new MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesRequestBody();
            inValue.Body.fromYear = fromYear;
            inValue.Body.tooYear = tooYear;
            MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesResponse retVal = ((MyWindowsFormApplication.ServiceCandidates.CandidatesAmericaRepublicanSoap)(this)).GetAllCandidates(inValue);
            return retVal.Body.GetAllCandidatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesResponse> MyWindowsFormApplication.ServiceCandidates.CandidatesAmericaRepublicanSoap.GetAllCandidatesAsync(MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesRequest request) {
            return base.Channel.GetAllCandidatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesResponse> GetAllCandidatesAsync(string fromYear, string tooYear) {
            MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesRequest inValue = new MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesRequest();
            inValue.Body = new MyWindowsFormApplication.ServiceCandidates.GetAllCandidatesRequestBody();
            inValue.Body.fromYear = fromYear;
            inValue.Body.tooYear = tooYear;
            return ((MyWindowsFormApplication.ServiceCandidates.CandidatesAmericaRepublicanSoap)(this)).GetAllCandidatesAsync(inValue);
        }
    }
}
