//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWindowsFormApplication.ServiceAmerican {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAmerican.AmericanSoap")]
    public interface AmericanSoap {
        
        // CODEGEN: Generating message contract since element name year from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckAmericanWar", ReplyAction="*")]
        MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarResponse CheckAmericanWar(MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckAmericanWar", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarResponse> CheckAmericanWarAsync(MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckAmericanWarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckAmericanWar", Namespace="http://tempuri.org/", Order=0)]
        public MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarRequestBody Body;
        
        public CheckAmericanWarRequest() {
        }
        
        public CheckAmericanWarRequest(MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckAmericanWarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string year;
        
        public CheckAmericanWarRequestBody() {
        }
        
        public CheckAmericanWarRequestBody(string year) {
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckAmericanWarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckAmericanWarResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarResponseBody Body;
        
        public CheckAmericanWarResponse() {
        }
        
        public CheckAmericanWarResponse(MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckAmericanWarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyWindowsFormApplication.ServiceAmerican.ArrayOfString CheckAmericanWarResult;
        
        public CheckAmericanWarResponseBody() {
        }
        
        public CheckAmericanWarResponseBody(MyWindowsFormApplication.ServiceAmerican.ArrayOfString CheckAmericanWarResult) {
            this.CheckAmericanWarResult = CheckAmericanWarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AmericanSoapChannel : MyWindowsFormApplication.ServiceAmerican.AmericanSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AmericanSoapClient : System.ServiceModel.ClientBase<MyWindowsFormApplication.ServiceAmerican.AmericanSoap>, MyWindowsFormApplication.ServiceAmerican.AmericanSoap {
        
        public AmericanSoapClient() {
        }
        
        public AmericanSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AmericanSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmericanSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmericanSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarResponse MyWindowsFormApplication.ServiceAmerican.AmericanSoap.CheckAmericanWar(MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarRequest request) {
            return base.Channel.CheckAmericanWar(request);
        }
        
        public MyWindowsFormApplication.ServiceAmerican.ArrayOfString CheckAmericanWar(string year) {
            MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarRequest inValue = new MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarRequest();
            inValue.Body = new MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarRequestBody();
            inValue.Body.year = year;
            MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarResponse retVal = ((MyWindowsFormApplication.ServiceAmerican.AmericanSoap)(this)).CheckAmericanWar(inValue);
            return retVal.Body.CheckAmericanWarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarResponse> MyWindowsFormApplication.ServiceAmerican.AmericanSoap.CheckAmericanWarAsync(MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarRequest request) {
            return base.Channel.CheckAmericanWarAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarResponse> CheckAmericanWarAsync(string year) {
            MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarRequest inValue = new MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarRequest();
            inValue.Body = new MyWindowsFormApplication.ServiceAmerican.CheckAmericanWarRequestBody();
            inValue.Body.year = year;
            return ((MyWindowsFormApplication.ServiceAmerican.AmericanSoap)(this)).CheckAmericanWarAsync(inValue);
        }
    }
}
