//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWindowsFormApplication.ServiceNameDay {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNameDay.GetNameDayServiceSoap")]
    public interface GetNameDayServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetName", ReplyAction="*")]
        MyWindowsFormApplication.ServiceNameDay.GetNameResponse GetName(MyWindowsFormApplication.ServiceNameDay.GetNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetName", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWindowsFormApplication.ServiceNameDay.GetNameResponse> GetNameAsync(MyWindowsFormApplication.ServiceNameDay.GetNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetName", Namespace="http://tempuri.org/", Order=0)]
        public MyWindowsFormApplication.ServiceNameDay.GetNameRequestBody Body;
        
        public GetNameRequest() {
        }
        
        public GetNameRequest(MyWindowsFormApplication.ServiceNameDay.GetNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetNameRequestBody() {
        }
        
        public GetNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWindowsFormApplication.ServiceNameDay.GetNameResponseBody Body;
        
        public GetNameResponse() {
        }
        
        public GetNameResponse(MyWindowsFormApplication.ServiceNameDay.GetNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNameResult;
        
        public GetNameResponseBody() {
        }
        
        public GetNameResponseBody(string GetNameResult) {
            this.GetNameResult = GetNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetNameDayServiceSoapChannel : MyWindowsFormApplication.ServiceNameDay.GetNameDayServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNameDayServiceSoapClient : System.ServiceModel.ClientBase<MyWindowsFormApplication.ServiceNameDay.GetNameDayServiceSoap>, MyWindowsFormApplication.ServiceNameDay.GetNameDayServiceSoap {
        
        public GetNameDayServiceSoapClient() {
        }
        
        public GetNameDayServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetNameDayServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetNameDayServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetNameDayServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWindowsFormApplication.ServiceNameDay.GetNameResponse MyWindowsFormApplication.ServiceNameDay.GetNameDayServiceSoap.GetName(MyWindowsFormApplication.ServiceNameDay.GetNameRequest request) {
            return base.Channel.GetName(request);
        }
        
        public string GetName(string name) {
            MyWindowsFormApplication.ServiceNameDay.GetNameRequest inValue = new MyWindowsFormApplication.ServiceNameDay.GetNameRequest();
            inValue.Body = new MyWindowsFormApplication.ServiceNameDay.GetNameRequestBody();
            inValue.Body.name = name;
            MyWindowsFormApplication.ServiceNameDay.GetNameResponse retVal = ((MyWindowsFormApplication.ServiceNameDay.GetNameDayServiceSoap)(this)).GetName(inValue);
            return retVal.Body.GetNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWindowsFormApplication.ServiceNameDay.GetNameResponse> MyWindowsFormApplication.ServiceNameDay.GetNameDayServiceSoap.GetNameAsync(MyWindowsFormApplication.ServiceNameDay.GetNameRequest request) {
            return base.Channel.GetNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWindowsFormApplication.ServiceNameDay.GetNameResponse> GetNameAsync(string name) {
            MyWindowsFormApplication.ServiceNameDay.GetNameRequest inValue = new MyWindowsFormApplication.ServiceNameDay.GetNameRequest();
            inValue.Body = new MyWindowsFormApplication.ServiceNameDay.GetNameRequestBody();
            inValue.Body.name = name;
            return ((MyWindowsFormApplication.ServiceNameDay.GetNameDayServiceSoap)(this)).GetNameAsync(inValue);
        }
    }
}
