//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWindowsFormApplication.ServiceAddTwoNumbers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAddTwoNumbers.AddTwoNumbersSoap")]
    public interface AddTwoNumbersSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoNumber", ReplyAction="*")]
        decimal AddTwoNumber(decimal numberOne, decimal numberTwo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> AddTwoNumberAsync(decimal numberOne, decimal numberTwo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddTwoNumbersSoapChannel : MyWindowsFormApplication.ServiceAddTwoNumbers.AddTwoNumbersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddTwoNumbersSoapClient : System.ServiceModel.ClientBase<MyWindowsFormApplication.ServiceAddTwoNumbers.AddTwoNumbersSoap>, MyWindowsFormApplication.ServiceAddTwoNumbers.AddTwoNumbersSoap {
        
        public AddTwoNumbersSoapClient() {
        }
        
        public AddTwoNumbersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddTwoNumbersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddTwoNumbersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddTwoNumbersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal AddTwoNumber(decimal numberOne, decimal numberTwo) {
            return base.Channel.AddTwoNumber(numberOne, numberTwo);
        }
        
        public System.Threading.Tasks.Task<decimal> AddTwoNumberAsync(decimal numberOne, decimal numberTwo) {
            return base.Channel.AddTwoNumberAsync(numberOne, numberTwo);
        }
    }
}
